sudo: false
language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6

env:
    - ASYNC_TEST_TIMEOUT=30
install:
    - pip install --upgrade setuptools pip
    - python setup.py bdist_wheel sdist
    - pip install dist/*.whl coverage
    - pip list
    - pip freeze
script:
    - jupyter enterprisegateway --help
    - nosetests -x --nocapture --process-restartworker --with-coverage --cover-package=enterprise_gateway
    - pip uninstall -y jupyter_enterprise_gateway
