language: python

python:
    - 3.5
    - 3.6
    - 3.7
    - 3.8

services:
    - docker

cache:
    directories:
     - /home/travis/.sbt/

env:
  global:
    - ASYNC_TEST_TIMEOUT=30

before_install:
    - mkdir -p $HOME/.sbt/launchers/1.2.1
    - curl -L -o $HOME/.sbt/launchers/1.2.1/sbt-launch.jar https://repo1.maven.org/maven2/org/scala-sbt/sbt-launch/1.2.1/sbt-launch.jar

install:
    - pip install --upgrade setuptools pip websocket-client flake8
    - travis_retry make clean dist enterprise-gateway-demo
    - pip install dist/*.whl coverage
    - pip freeze

script:
    - jupyter enterprisegateway --help
    - flake8 enterprise_gateway
    - travis_retry travis_wait 3 nosetests -x --process-restartworker --with-coverage --cover-package=enterprise_gateway enterprise_gateway.tests
    - echo "Starting integration tests ..."
    - make itest-yarn
    - pip uninstall -y jupyter_enterprise_gateway

after_success:
  - echo "Travis exited with ${TRAVIS_TEST_RESULT}"
  - python --version
  - pip --version
  - pip list
  - docker logs itest-yarn
  - pip install codecov
  - codecov

after_failure:
  - echo "Travis exited with ${TRAVIS_TEST_RESULT}"
  - python --version
  - pip --version
  - pip list
  - docker logs itest-yarn
