image: elyra/enterprise-gateway:dev
imagePullPolicy: IfNotPresent
replicas: 1
kernel_cluster_role: "kernel-controller"
shared_namespace: false
mirror_working_dirs: false
cull_idle_timeout: 3600
log_level: "DEBUG"
kernel_launch_timeout: 60
kernel_whitelist:
  - r_kubernetes
  - python_kubernetes
  - python_tf_kubernetes
  - python_tf_gpu_kubernetes
  - scala_kubernetes
  - spark_r_kubernetes
  - spark_python_kubernetes
  - spark_scala_kubernetes

nfs:
  # Set to true to enable NFS-mounted kernelspecs.
  enabled: false
  internal_server_ip_address:

# Set in order to use <k8s-master>:8888.
k8s_master_public_ip:
